### ISSUE TITLE
[Feature] Add possibility for CDN usage

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/cc-assets#2]
## Problem
This repo currently contains images in different folders but doesn't quite expose a  module that can be imported and utilized.

## Description
We should export a module with a switch case function that returns an image based on its slug.

## Alternatives
Leave as is.

## Additional context
- [Javascript Modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by MuluhGodson** [comment]
@brylie I am considering closing this issue unless there is a need to someday use this `cc-assets` package via CDN. Is this something you forsee may be of need?

**Comment by brylie** [comment]
Since we are publishing the `cc-assets` package to NPM, we already benefit from the unpkg CDN

https://unpkg.com/
